name: Deploy to Cloudflare Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    env:
      # NODE_VERSION is now read from .nvmrc
      CLOUDFLARE_PROJECT_NAME: ${{ vars.CLOUDFLARE_PROJECT_NAME }} # Set in GitHub repository variables

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read .nvmrc
        id: nvm
        run: echo "::set-output name=NODE_VERSION::$(cat .nvmrc)"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
          cache: 'npm' # Cache npm dependencies

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        run: npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }} # Set in GitHub repository secrets
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }} # Set in GitHub repository variables
          command: pages deploy dist --project-name=${{ env.CLOUDFLARE_PROJECT_NAME }}
          # Optional: Enable GitHub Deployments
          # gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Enable wrangler caching for faster deployments
          # wranglerVersion: '3' 