name: PR Checks

on:
  pull_request:
    branches: [ master ] # Adjust if your main branch is different

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup
        run: |
          rm -rf package-lock.json node_modules
          npm install
        
      - name: Run unit tests with coverage
        run: npm run test:unit -- --coverage
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          # Add any other test-time environment variables here

      # Optional: Upload coverage artifact
      # - name: Upload coverage reports
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: coverage-report
      #     path: coverage/ # Adjust path if vitest outputs coverage elsewhere

  summarize:
    name: Summarize Checks
    runs-on: ubuntu-latest
    needs: [lint, test] # Run this job after lint and test complete
    if: always() # Run this job even if previous jobs fail
    permissions:
      pull-requests: write # Need permission to write comments
    steps:
      - name: Create summary comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## PR Check Summary

            **Lint:** ${{ needs.lint.result == 'success' && ':white_check_mark: Passed' || ':x: Failed' }}
            **Unit Tests:** ${{ needs.test.result == 'success' && ':white_check_mark: Passed' || ':x: Failed' }}

            *Workflow run: [${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})*
          edit-mode: replace # Replace previous comment from this workflow if it exists 